name = "my-hyde"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.53

[author]
    name = "Nixon Enraght-Moony"
    homepage = "Under construction"

# If Porting existing theme
[original]
    author =  "Steve Francia"
    homepage = "https://spf13.com/"
    repo = "https://github.com/spf13/hyde"
